version: "3.4"
services: 
    text-analyzer:
        container_name: text-analyzer
        image: text-analyzer
        build: 
            context: ../text-analyzer
        volumes: 
            - ../text-analyzer:/app/text-analyzer
        ports: 
            - "8000:8000"
        command: sh -c "python /app/text-analyzer/manage.py runserver 0.0.0.0:8000"
    
    db:
        container_name: app-database
        image: postgres:13-alpine
        restart: always
        environment: 
            POSTGRES_PASSWORD: 10242048
        volumes:
            - ./postgres-docker-init.d:/docker-entrypoint-initdb.d
            - ~/.social-app-docker/app-database/data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    
    client:
        container_name: app-client
        image: app-client
        build:
            context: ../social-app-client
        depends_on: 
            - server
        volumes:
            - ../social-app-client:/app/client
            - /app/clinet/node_modules
        ports:
            - "3080:3000"
        command: bash -c "yarn start"

    server:
        container_name: app-server
        image: app-server
        build:
            context: ../social-app-server
        depends_on:
            - db
            - text-analyzer
        volumes:
          - "../social-app-server:/app/server"
        ports:
          - "9090:9090"
          - "5005:5005"
        restart: on-failure
        healthcheck:
            test: curl --fail http://app-server:9090/_health || exit 1
            interval: 5s
            retries: 5
            start_period: 2s
            timeout: 2s
        command: bash -c "mvn spring-boot:run -Dspring-boot.run.jvmArguments=\"-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005\""
